var DariPattern=function(config){'use strict';if(config===undefined||config===null){config={};}
this.config={patternType:(config.patternType)?config.patternType:'odd_even',getType:(config.getType)?config.getType:'date',getData:(config.getData)?config.getData:new Date().format('yyyy-MM-dd'),templateId:(config.templateId)?config.templateId:'pattern-template',parentWrapperId:(config.parentWrapperId)?config.parentWrapperId:'pattern',wrapperId:(config.wrapperId)?config.wrapperId:'pattern-box',patternBoxWidth:(config.patternBoxWidth)?config.patternBoxWidth:34,patternWidthType:(config.patternWidthType)?config.patternWidthType:'dataCount'};this.patternSixRes=null;};DariPattern.prototype.autoScroll=function(){'use strict';var $wrapper=$('#'+ this.config.wrapperId);$wrapper.parent('.box_area').animate({scrollLeft:$wrapper.width()},100);};DariPattern.prototype.render=function(res,context){'use strict';var html,$patternElement=$('#'+ context.config.wrapperId);if(!res.data||res.data.length===0){dataNotFoundHandlerForDiv(this.config.wrapperId,'패턴 데이터가 존재하지 않습니다.');return false;}
html=new EJS({element:context.config.templateId}).render(res);if(context.config.patternWidthType=='dlCount'){$patternElement.html(html);context.patternSixRes=res;$patternElement.css('width',$patternElement.find('dl').length*context.config.patternBoxWidth+'px');}else{$patternElement.append(html);$patternElement.css('width',res.data.length*context.config.patternBoxWidth+'px');context.analysisRender(res,context);}
context.autoScroll();try{if(typeof parent.resizeFrame==='function'){parent.resizeFrame();}}catch(e){}};DariPattern.prototype.analysisRender=function(res,context){'use strict';var totalCount=0;var analysisArray=new Array();var i=0,j=0,idx=0,key='';var row,value;var p=0,pMax=0;var html='';for(i in res.data){row=res.data[i];value=row.value;idx=null;for(j=0;j<analysisArray.length;j++){if(analysisArray[j].value==value){idx=j;break;}}
if(idx==null){idx=analysisArray.length;analysisArray[idx]=new Object({'value':value,'value_alias':row.value_alias,'value_count':0,'value_max_count':0});}
if(row.count>analysisArray[idx].value_max_count){analysisArray[idx].value_max_count=row.count;}
if(p>0&&row.count==1){p++;if(p>pMax){pMax=p;}}else{p=1;}
analysisArray[idx].value_count+=row.count;totalCount+=row.count;}
for(i in analysisArray){key=analysisArray[i]['value'];analysisArray[key]=analysisArray[i];}
switch(context.config.patternType){case'start_point':totalCount=(analysisArray['LEFT'].value_count+ analysisArray['RIGHT'].value_count);html+=context.getAnalysisStatHTML(analysisArray['LEFT'],totalCount);html+=context.getAnalysisStatHTML(analysisArray['RIGHT'],totalCount);break;case'line_count':totalCount=(analysisArray['3'].value_count+ analysisArray['4'].value_count);html+=context.getAnalysisStatHTML(analysisArray['3'],totalCount);html+=context.getAnalysisStatHTML(analysisArray['4'],totalCount);break;case'odd_even':totalCount=(analysisArray['ODD'].value_count+ analysisArray['EVEN'].value_count);html+=context.getAnalysisStatHTML(analysisArray['ODD'],totalCount);html+=context.getAnalysisStatHTML(analysisArray['EVEN'],totalCount);break;case'under_over':totalCount=(analysisArray['UNDER'].value_count+ analysisArray['OVER'].value_count+ analysisArray['X'].value_count);html+=context.getAnalysisStatHTML(analysisArray['UNDER'],totalCount);html+=context.getAnalysisStatHTML(analysisArray['OVER'],totalCount);html+=context.getAnalysisStatHTML(analysisArray['X'],totalCount);break;case'start_line':totalCount=(analysisArray['LEFT4ODD'].value_count+ analysisArray['RIGHT3ODD'].value_count+ analysisArray['LEFT3EVEN'].value_count+ analysisArray['RIGHT4EVEN'].value_count);html+=context.getAnalysisStatHTML(analysisArray['LEFT4ODD'],totalCount);html+=context.getAnalysisStatHTML(analysisArray['RIGHT3ODD'],totalCount);html+=context.getAnalysisStatHTML(analysisArray['LEFT3EVEN'],totalCount);html+=context.getAnalysisStatHTML(analysisArray['RIGHT4EVEN'],totalCount);break;}
if(context.config.patternType!='start_line'){html+='<li class="etc">'+ res.data.length+'번 꺽음('+ pMax+'퐁당)</li>';}
$('#'+ context.config.parentWrapperId).find('.info').html(html);};DariPattern.prototype.getAnalysisStatHTML=function(array,totalCount){var html='';if(array!=null){if(array.value=='3'){array.value='line3';array.value_alias='3';}else if(array.value=='4'){array.value='line4';array.value_alias='4';}
array.per_value=Math.round((array.value_count/totalCount*10000))/ 100;
html='<li class="'+ array.value.toLowerCase()+'"><span class="ic">'+ array.value_alias+'</span><p class="tx"><strong>'+array.value_count+'번</strong> ('+ array.per_value+'%) '+ array.value_max_count+'연속</p></li>';}
return html;}
DariPattern.prototype.reset=function(){'use strict';var $wrapper=$('#'+ this.config.wrapperId);if($wrapper.length>0){$wrapper.empty();}};DariPattern.prototype.select=function(){'use strict';this.reset();statsAPI.dari.getPattern(this.config.patternType,this.config.getType,this.config.getData,this.render,this);};DariPattern.prototype.renderStat=function(res,context){'use strict';var html,$patternElement=$('#'+ context.config.wrapperId);if(!res.data||res.data.length===0){dataNotFoundHandlerForDiv(this.config.wrapperId,'패턴 데이터가 존재하지 않습니다.');return false;}
html=new EJS({element:context.config.templateId}).render(res);$patternElement.append(html);context.autoScroll();if(typeof parent.resizeFrame==='function'){parent.resizeFrame();}}
DariPattern.prototype.selectStat=function(){'use strict';this.reset();statsAPI.dari.getPatternStat(this.config.patternType,this.config.getType,this.config.getData,this.renderStat,this);};